### ISSUE TITLE
Admin music button doesn't work

### ISSUE THREAD

**Issue by WhyIsCaeciliusTaken** [BeeStation/BeeStation-Hornet#1161]
## Round ID:
11995
## Reproduction:

Try to play music using the "play internet sound" button
Get an error message:

Youtube-dl URL retrieval FAILED:
ERROR: Signature extraction failed: Traceback (most recent call last):
 File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphopugs4t\build\youtube_dl\extractor\youtube.py", line 1378, in _decrypt_signature
 File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphopugs4t\build\youtube_dl\extractor\youtube.py", line 1291, in _extract_signature_function
 File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphopugs4t\build\youtube_dl\extractor\youtube.py", line 1354, in 
 File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphopugs4t\build\youtube_dl\jsinterp.py", line 258, in resf
 File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphopugs4t\build\youtube_dl\jsinterp.py", line 56, in interpret_statement
 File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphopugs4t\build\youtube_dl\jsinterp.py", line 92, in interpret_expression
 File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphopugs4t\build\youtube_dl\jsinterp.py", line 189, in interpret_expression
 File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphopugs4t\build\youtube_dl\jsinterp.py", line 56, in interpret_statement
 File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmphopugs4t\build\youtube_dl\jsinterp.py", line 211, in interpret_expression
youtube_dl.utils.ExtractorError: Unsupported JS expression '[1999057972,'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Unsupported JS expression '[1999057972,'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by WhyIsCaeciliusTaken** [comment]
Strangely, "Curb your enthusiasm" works, but nothing else that I know of.

**Comment by Crossedfall** [comment]
Youtube-dl likely broke again. Happens from time to time since youtube really doesn't like these kinds of extensions. I'll see if there's an updated version I can get

**Comment by Crossedfall** [comment]
Forgot to close this, updated the DL and things seem to be working again.
