### ISSUE TITLE
Paper cannot be written on

### ISSUE THREAD

**Issue by Purpfarm** [BeeStation/BeeStation-Hornet#6205]
Issue reported from  Round ID: 35479 (BeeStation Sage - Roleplay)

Reporting client version: 514.1571

As curator attempted to write on a paper both in hand and on desk multiple times with multiple pens and papers. every time it came up with a Bluescreen NTOS error. This is the Error Stack copied from the bluescreen:

TypeError: Object expected
   at Anonymous function (http://127.0.0.1:64377/tmp23280/tgui.bundle.js:1:432327)
   at n.createPreview (http://127.0.0.1:64377/tmp23280/tgui.bundle.js:1:432313)
   at Anonymous function (http://127.0.0.1:64377/tmp23280/tgui.bundle.js:1:433644)
   at He (http://127.0.0.1:64377/tmp23280/tgui-common.bundle.js:1:181286)
   at Ge.prototype.setState (http://127.0.0.1:64377/tmp23280/tgui-common.bundle.js:1:182305)
   at n.onInputHandler (http://127.0.0.1:64377/tmp23280/tgui.bundle.js:1:433618)
   at o.handleOnInput (http://127.0.0.1:64377/tmp23280/tgui-common.bundle.js:1:347540)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; Tablet PC 2.0; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Zoom 3.6.0)
State: {"ckey":"leafvixen","interface":"PaperSheet","window":{"key":"[0x202c44a]-main","size":null,"fancy":1,"locked":1}}

TypeError: Object expected
   at Anonymous function (http://127.0.0.1:64377/tmp23280/tgui.bundle.js:1:432327)
   at n.createPreview (http://127.0.0.1:64377/tmp23280/tgui.bundle.js:1:432313)
   at Anonymous function (http://127.0.0.1:64377/tmp23280/tgui.bundle.js:1:433644)
   at He (http://127.0.0.1:64377/tmp23280/tgui-common.bundle.js:1:181286)
   at Ge.prototype.setState (http://127.0.0.1:64377/tmp23280/tgui-common.bundle.js:1:182305)
   at n.onInputHandler (http://127.0.0.1:64377/tmp23280/tgui.bundle.js:1:433618)
   at o.handleOnInput (http://127.0.0.1:64377/tmp23280/tgui-common.bundle.js:1:347540)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; Tablet PC 2.0; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Zoom 3.6.0)
State: {"ckey":"leafvixen","interface":"PaperSheet","window":{"key":"[0x202c44a]-main","size":null,"fancy":1,"locked":1}}

TypeError: Object expected
   at Anonymous function (http://127.0.0.1:64377/tmp23280/tgui.bundle.js:1:432327)
   at n.createPreview (http://127.0.0.1:64377/tmp23280/tgui.bundle.js:1:432313)
   at Anonymous function (http://127.0.0.1:64377/tmp23280/tgui.bundle.js:1:433644)
   at He (http://127.0.0.1:64377/tmp23280/tgui-common.bundle.js:1:181286)
   at Ge.prototype.setState (http://127.0.0.1:64377/tmp23280/tgui-common.bundle.js:1:182305)
   at n.onInputHandler (http://127.0.0.1:64377/tmp23280/tgui.bundle.js:1:433618)
   at o.handleOnInput (http://127.0.0.1:64377/tmp23280/tgui-common.bundle.js:1:347540)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; Tablet PC 2.0; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Zoom 3.6.0)
State: {"ckey":"leafvixen","interface":"PaperSheet","window":{"key":"[0x202c44a]-main","size":null,"fancy":1,"locked":1}}

**Comment by OverwatchVoice** [comment]
Also having this issue when writing on paper.

**Comment by Archanial** [comment]
TGUI dev server also isn't working.
https://github.com/BeeStation/BeeStation-Hornet/pull/6186
might be where the issue is coming from
